### ISSUE TITLE
Can't run the prep tools 

### ISSUE THREAD

**Issue by starwingc** [starwingc/peptoid_24summer#1]
@vvoelz 
Can you help to check up the /peptoid/test/73C_0, the test run? I think I make sure all the atomic name are distinct, and with the correct cappingatomis.txt. 
however, there is still some error when I try to run:

```
python ~/Voelz_Lab/git/prep-tools/scripts/build_amber_residue.py -s N -t C 73C.mol2 73C capping_atoms.txt X G 0

```

and the error:

```
(AmberTools20) starwingchen@90-9c-4a-cf-d5-8d 73C_0 % python ~/Voelz_Lab/git/prep-tools/scripts/build_amber_residue.py -s N -t C 73C.mol2 73C capping_atoms.txt X G 0
prep-tools, Version 1.0
Environment variable AMBERHOME = /Users/starwingchen/anaconda3/envs/AmberTools20 exists.
Environment variable AMBERHOME = /Users/starwingchen/anaconda3/envs/AmberTools20 exists.
AMBERHOME = /Users/starwingchen/anaconda3/envs/AmberTools20
Building from file 73C.mol2 ...
>> antechamber -i 73C.mol2 -fi mol2 -o 73C.preedit.mol2 -fo mol2 -at gaff -nc 0 -ek "scfconv=1.d-7 tight_p_conv=0" -j 5 -c bcc
b'\nWelcome to antechamber 20.0: molecular input file processor.\n\nacdoctor mode is on: check and diagnose problems in the input file.\n-- Check Format for mol2 File --\n   Status: pass\n-- Check Unusual Elements --\n   Status: pass\n-- Check Open Valences --\n   Status: pass\n-- Check Geometry --\n      for those bonded   \n      for those not bonded   \n   Status: pass\n-- Check Weird Bonds --\n   Status: pass\n-- Check Number of Units --\n   Status: pass\nacdoctor mode has completed checking the input file.\n\n\nInfo: Total number of electrons: 134; net charge: 0\n\nRunning: /Users/starwingchen/anaconda3/envs/AmberTools20/bin/sqm -O -i sqm.in -o sqm.out\n\n'
Traceback (most recent call last):
  File "/Users/starwingchen/Voelz_Lab/git/prep-tools/scripts/build_amber_residue.py", line 201, in <module>
    out_mol2 = build_antechamber(p.InputFileName, p.ResidueName, CappingAtoms, p.CNTerm, p.Forcefield, p.NetCharge, HeadAtom=p.HeadAtom, TailAtom=p.TailAtom)
  File "/Users/starwingchen/Voelz_Lab/git/prep-tools/scripts/build_amber_residue.py", line 82, in build_antechamber
    ResObject=Mol2File(in_mol2)#Casts the mol2file object type to the residue so that the edit_charge and net_charge methods can be called on it
  File "/Users/starwingchen/anaconda3/envs/AmberTools20/lib/python3.9/site-packages/preptools-1.0a1-py3.9.egg/preptools/fileclasses/molecules/Mol2File.py", line 38, in __init__
IndexError: list index out of range

```

**Comment by starwingc** [comment]
All the residue's name should be full alphabet.
